sudo: false
language: node_js
node_js:
  - "6"
before_install: cd redux
cache:
  directories:
  - $HOME/.yarn-cache
install:
  - npm install -g yarn
  - yarn install
script: yarn test
notifications:
  email: false
