sudo: false
language: node_js
node_js:
  - "4"
before_install: cd redux
install: npm install
script: npm test
notifications:
  slack:
    secure: t18EZ3yf6MEUZWT+5sP6AN0BdFG62BUNMi4kESDA8S9CqlZZUDdKGs7AhKOE0Bcc1UjZ/8GA9EELMD5VQvPoxllnUpBykti+86mvRG7rt7ThSVYPH7kq1qdJY+0LFLJZsMX8XD8DhNDutdMmGv1PY1nmJ6QheOqXhz0McTkqRVwxrJ3YIR5R22er0X1khm+L3i5QkZY5b6trGqygQJTxWzjAXEcza8sC5xR8xVKQJgtT5Z2HU8Yn3pqDnl+Pdjp++RfVIzL4cgWiFQ8MaTHQBAxFSBhgX8HD590zUuHSaf/KkGO0YMaVLfD/UaB0432pSLrrNZGcUGqCBMiRZwQkvFQbFhlBlkpYfg0dQc9pn1R4Hpl2RxmpXdPoYPcN7kijmbtIgiBTgOkNj8O1xB4w1T09YVSAgVgSOr9ZaucEPgeGpPSLU7WmRNOu9fr1IUvO6iAxdXy8kSnm6RpIdeVFDkeKVmaVjIcdtuf9yo6bJq14vAvAoJgNfht+qdzmJpz9W1TBGyQU43ppYframJm2wlrmtg8CJaJsJmec3ypF2ToUxODMguYNbu+BBBFgOQfmWGt+1YrF8tT8j6a29nFamW+H1iITrIgcO8uudCjd2hOa8hM1No6SEaWuLReq1SjR1J5V830US+hwDWzeMuztKrLpYA7Eu1oCJes7Z7oO5cs=
