export const RECEIVED_ACCOUNT = 'RECEIVED_ACCOUNT';

export const RECEIVED_HOME_TIMELINE = 'RECEIVED_HOME_TIMELINE';

export const POSTED_TWEET = 'POSTED_TWEET';

export const CREATED_FAVORITED = 'CREATED_FAVORITED';
export const DESTROYED_FAVORITE = 'DESTROYED_FAVORITE';
