// account
export const RECEIVED_ACCOUNT         = 'RECEIVED_ACCOUNT';
export const REPLACE_ACCOUNTS         = 'REPLACE_ACCOUNTS';
export const REMOVE_ACCOUNT           = 'REMOVE_ACCOUNT';
export const SWITCHED_PRIMARY_ACCOUNT = 'SWITCHED_PRIMARY_ACCOUNT';


// home timeline
export const REFRESH_HOME_TIMELINE = 'REFRESH_HOME_TIMELINE';
export const RECEIVED_HOME_TIMELINE = 'RECEIVED_HOME_TIMELINE';
export const RECEIVED_OLD_HOME_TIMELINE = 'RECEIVED_OLD_HOME_TIMELINE';

//my timeline
export const RECEIVED_MY_TIMELINE = 'RECEIVED_MY_TIMELINE';
export const RECEIVED_OLD_MY_TIMELINE = 'RECEIVED_OLD_MY_TIMELINE';

//following
export const RECEIVED_FOLLOWING = 'RECEIVED_FOLLOWING';
export const RECEIVED_OLD_FOLLOWING = 'RECEIVED_OLD_FOLLOWING';
export const RECEIVED_FOLLOWING_COMPLETED = 'RECEIVED_FOLLOWING_COMPLETED';

//followers
export const RECEIVED_FOLLOWERS = 'RECEIVED_FOLLOWERS';
export const RECEIVED_OLD_FOLLOWERS = 'RECEIVED_OLD_FOLLOWERS';
export const RECEIVED_FOLLOWERS_COMPLETED = 'RECEIVED_FOLLOWERS_COMPLETED';

//lists
export const RECEIVED_OWN_LISTS = 'RECEIVED_OWN_LISTS';

//tweetsInList
export const RECEIVED_FIRST_TWEETS_IN_LIST = 'RECEIVED_FIRST_TWEETS_IN_LIST';
export const RECEIVED_OLDER_TWEETS_IN_LIST = 'RECEIVED_OLDER_TWEETS_IN_LIST';

export const POSTED_TWEET = 'POSTED_TWEET';

export const CREATED_FAVORITE = 'CREATED_FAVORITE';
export const DESTROYED_FAVORITE = 'DESTROYED_FAVORITE';
export const RECEIVED_MY_FAVORITES = 'RECEIVED_MY_FAVORITES';
export const RECEIVED_MY_OLD_FAVORITES = 'RECEIVED_MY_OLD_FAVORITES';

//users
export const RECEIVED_USER = 'RECEIVED_USER';

//error message
export const ADD_ERROR_MESSAGE = 'ADD_ERROR_MESSAGE';
