export const RECEIVED_ACCOUNT = 'RECEIVED_ACCOUNT';


// home timeline
export const RECEIVED_HOME_TIMELINE = 'RECEIVED_HOME_TIMELINE';
export const RECEIVED_OLD_HOME_TIMELINE = 'RECEIVED_OLD_HOME_TIMELINE';

//my timeline
export const RECEIVED_MY_TIMELINE = 'RECEIVED_MY_TIMELINE';
export const RECEIVED_OLD_MY_TIMELINE = 'RECEIVED_OLD_MY_TIMELINE';

//following
export const RECEIVED_FOLLOWING = 'RECEIVED_FOLLOWING';

export const POSTED_TWEET = 'POSTED_TWEET';

export const CREATED_FAVORITE = 'CREATED_FAVORITE';
export const DESTROYED_FAVORITE = 'DESTROYED_FAVORITE';
export const RECEIVED_MY_FAVORITES = 'RECEIVED_MY_FAVORITES';
export const RECEIVED_MY_OLD_FAVORITES = 'RECEIVED_MY_OLD_FAVORITES';
